export const ActionsTypes = {
  SET_LOADING: "SET_LOADING",
  SET_PRODUCT: "SET_PRODUCT",
  SET_BASKET_ERROR: "SET_BASKET_ERROR",
  SET_BASKET: "SET_BASKET",
  SET_BASKET_LOADING: "SET_BASKET_LOADİNG",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  UPDATE_ITEM: "UPDATE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  SET_ERROR: "SET_ERROR"
};
